### ISSUE TITLE
transient-universe-0.3.2.3 fails to build with transient-0.4.4

### ISSUE THREAD

**Issue by juhp** [transient-haskell/transient-universe#15]
```
src/Transient/Move.hs:183:24: error:
    • No instance for (Typeable a) arising from a use of ‘keep’
    • In the expression: keep mx
      In an equation for ‘runCloudIO’: runCloudIO (Cloud mx) = keep mx

src/Transient/Move.hs:187:25: error:
    • No instance for (Typeable a) arising from a use of ‘keep'’
    • In the expression: keep' mx
      In an equation for ‘runCloudIO'’: runCloudIO' (Cloud mx) = keep' mx

src/Transient/Move.hs:288:16: error:
    Variable not in scope: finish :: Maybe SomeException -> TransIO ()

src/Transient/Move.hs:814:4: error:
    Variable not in scope: initFinish :: TransIO a2

src/Transient/Move.hs:815:4: error:
    Variable not in scope: onFinish :: (b0 -> m0 ()) -> TransIO a3

src/Transient/Move.hs:838:12: error:
    Variable not in scope:
      killOnFinish :: TransIO (StreamData b1) -> TransIO (StreamData a)

src/Transient/Move.hs:868:7: error:
    Variable not in scope: initFinish :: TransIO a4

src/Transient/Move.hs:869:7: error:
    Variable not in scope: onFinish :: (b2 -> m1 ()) -> TransIO a5

src/Transient/Move.hs:879:7: error:
    Variable not in scope:
      killOnFinish :: TransIO (StreamData a6) -> TransIO b

src/Transient/Move.hs:889:29: error:
    Variable not in scope: finish :: Maybe SomeException -> TransIO x0

src/Transient/Move.hs:892:34: error:
    Variable not in scope: finish :: Maybe a1 -> TransIO x1

src/Transient/Move.hs:1127:15: error:
    Variable not in scope: onFinish :: (b3 -> m2 ()) -> TransIO a7

src/Transient/Move.hs:1293:13: error:
    Variable not in scope:
      killOnFinish :: TransIO (StreamData a0) -> TransIO (StreamData a)
```

**Comment by geraldus** [comment]
Hey @juhp !  Thanks for the report!  Sorry for this inconveniences!  I hope we will do better build checks before move code to master in future.

**Comment by geraldus** [comment]
Ok, I have a hot fix, will update my currently opened pull request.  I can merge it after build check, but it will take a little to put new version on Hackage.
